allowBuilds:
  unrs-resolver: true

overrides:
  '@jrmajor/eslint-config@*>eslint-plugin-svelte': '-'
  '@jrmajor/eslint-config@*>@eslint/css': '-'
  '@jrmajor/eslint-config@*>tailwind-csstree': '-'

engineStrict: true
dedupePeers: true
strictDepBuilds: true
strictPeerDependencies: true
