name: Update readme

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  update-readme:
    name: Update readme

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0
          cache: pnpm

      - name: Install npm dependencies
        run: pnpm install --prod

      - name: Update Readme
        run: pnpm cli gen

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update readme
          branch: master
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
